### PR TITLE
removed yml files and improved style in ctd_request strings

### PR DESCRIPTION
**Pull request by FelixSchwock**

### CODE REVIEW

**Comment by John-Ragland** [comment]
There's an error that I wanted to fix with interpolated the calibration for low frequency hydrophones. Do you think this should be in this PR or a separate one?

**Comment by FelixSchwock** [comment]
You can put it in this one if its a smaller fix. If it's something bigger maybe a separate branch is better.

**Comment by John-Ragland** [comment]
should (hopefully) be a one line fix, I'll add it to this PR

**Review by John-Ragland — APPROVED** [review]

**Comment by John-Ragland** [comment]
Didn't end up fixing it. I'll investigate it later

**Pull request merged**
